apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
  namespace: greenroad
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 5
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - image: alexwhen/docker-2048
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: "2048"
  namespace: greenroad
  labels:
    app: servicelabel
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31234
  selector:
    app: "2048"
